loans:
  message: "Welcome to the Loans Microservice!"
  contactDetails:
    name: "Yassine ben kacem"
    email: "yassine@gmail.com"
  onCallSupport:
    - (+212) 123-456-7890
    - (+212) 987-654-3210