server:
  port: 8080
spring:

  application:
    name: "accounts"
  datasource:
    url: jdbc:mysql://localhost:3306/accountsdb
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"


  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

    function:
      definition: updateCommunication
    stream:
      bindings:
        updateCommunication-in-0:
          destination: communication-sent
          group: ${spring.application.name}
        sendCommunication-out-0:
          destination: send-communication

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 10s


management:
  endpoints:
    web:
      exposure:
        include: "*"
  prometheus:
    metrics:
      export:
        enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
    prometheus:
      access: unrestricted
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

  info:
    env:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}


# eureka client configs :

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
info:
  app:
    name: accounts
    description: "Accounts Microservice"
    version: 1.0.0
logging:
  level:
    com:
      bankApp:
        accountsMicroservice: DEBUG

  pattern:
    level: "%5p [${spring.application.name},%X{trace_id:-},%X{span_id:-}]"

resilience4j:
  circuitbreaker:
    configs:
       default:
        sliding-window-size: 10
        permitted-number-of-calls-in-half-open-state: 2
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 1000
  retry:
    configs:
      default:
        max-attempts: 3
        wait-duration: 100
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2

  ratelimiter:
    configs:
      default:
        timeout-duration: 1s
        limit-refresh-period: 5s
        limit-for-period: 1

