services:
  accounts:
    image: "yassinandkingo/accounts:bank"
    container_name: "accounts-ms"
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank-network

  loans:
    image: "yassinandkingo/loansmicroservice:bankApp"
    container_name: "loans-ms"
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - bank-network


  cards:
    image: "yassinandkingo/cardmicroservice:bankApp"
    container_name: "cards-ms"
    ports:
      - "9000:9000"

    deploy:
        resources:
            limits:
              memory: 700m
    networks:
        - bank-network


networks:
  bank-network:
    driver: bridge

